apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-configmap-majestic-hamilton-9dcd1c89c4
  namespace: apps-release
data:
  alloy.river: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    // OTLP Receiver for traces, metrics, and logs from the application SDK
    otelcol.receiver.otlp "app_otlp" {
      grpc {
        endpoint = "127.0.0.1:4317"
      }
      http {
        endpoint = "127.0.0.1:4318"
      }
      output {
        metrics = [otelcol.processor.batch.default.input]
        logs    = [otelcol.processor.batch.default.input]
      }
    }

    // Batch processor
    otelcol.processor.batch "default" {
      timeout         = "1s"
      send_batch_size = 1024
      output {
        metrics = [otelcol.exporter.prometheus.default.input]
        logs    = [otelcol.exporter.loki.default.input]
      }
    }

    // Loki Exporter (for OTLP logs)
    otelcol.exporter.loki "default" {
      forward_to = [loki.write.main.receiver]
    }

    // Loki Writer
    loki.write "main" {
      endpoint {
        url = "https://loki.backstract.io/loki/api/v1/push"
      }
      external_labels = {
        environment = "majestic-hamilton-9dcd1c89c4",
        source_type = "alloy_k8s_majestic-hamilton-9dcd1c89c4",
      }
    }

    // Prometheus Exporter
    otelcol.exporter.prometheus "default" {
      forward_to = [prometheus.remote_write.main.receiver]
    }

    // Prometheus Writer
    prometheus.remote_write "main" {
      endpoint {
        url = "https://prometheus.backstract.io/api/v1/write"
      }
    }
